apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: posion-pill-machine-health-check
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: "worker"
      machine.openshift.io/cluster-api-machine-type: "worker"
  unhealthyConditions:
  - type:    "Ready"
    timeout: "60s"
    status: "False"
  - type:    "Ready"
    timeout: "60s"
    status: "Unknown"
  remediationTemplate: 
    kind: PoisonPillRemediationTemplate
    apiVersion: poison-pill.medik8s.io/v1alpha1
    name: poisonpillremediationtemplate-sample
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: poison-pill-manager-alpha-redhat-operators-openshift-marketplace
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: poison-pill-manager
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: poison-pill.v0.2.0