apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: crdb-tester
  name: crdb-tester
spec:
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/master: ""
  containers:
  - command:
    - sh
    - "-c"
    - sleep 9999s
    image: cockroachdb/cockroach:v21.2.4
    name: crdb-tester
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always